# Package overview

package_name: "usedcar_model"


# Variables
# The variable we are attempting to predict (price)
target: price

pipeline_name: usedcar_model
pipeline_save_file: usedcar__model_output_v

training_data_file: vehicles.csv.aa

# Features that will go inside processing pipeline
features:
  - age # derived from year 
  - manufacturer
  - model
  - condition
  - cylinders
  - fuel
  - odometer
  - title_status
  - transmission
  - drive
  - size
  - type
  - paint_color
  - county
  - state

# Features to drop before pipeline
unused_fields:  
  - id
  - url
  - region_url
  - year
  - VIN
  - image_url
  - description
  - lat
  - long
  - posting_date
  - region

categorical_features:
  - manufacturer
  - model
  - condition
  - cylinders
  - fuel
  - title_status
  - transmission
  - drive
  - size
  - type
  - paint_color
  - county
  - state
  
# Set train/test split
test_size: 0.20


# Alogrithm parameters
n_estimators: 100
learning_rate: 0.1
max_depth: 5
subsample: 0.8
colsample_bytree: 0.8
objective: 'reg:squarederror'
random_state: 42
